hand_architecture: 'pr2'

frame_base: 'base_link'
frame_view_point: 'openni_rgb_optical_frame'
service_name_image_poll: '/prosilica/request_image'
rostopic_colored_image: '/camera/rgb/image_color'
rostopic_pickup_status: '/object_manipulator/object_manipulator_pickup/status'
frame_gripper: 'r_gripper_led_frame'
template_width: 0.15

gripper_bounding_corner1_x: -0.005
gripper_bounding_corner1_y: -0.12
gripper_bounding_corner1_z: -0.07

gripper_bounding_corner2_x: 0.16
gripper_bounding_corner2_y: 0.12
gripper_bounding_corner2_z: 0.02

template_extraction_offset_x: 0.08
template_extraction_offset_y: 0.0
template_extraction_offset_z: -0.025

default_viewpoint_x: 0.654406
default_viewpoint_y: 0.0302805
default_viewpoint_z: 1.09092

use_table_for_extraction: true

occlusion_punishment_fac: 0.0
learning_lib_qual_factor: 1.0
learning_fail_distance_factor: 1.0

learning_success_add_dist: 0.0