# request with feature filename and test or train, node listens to required topics on its own
string filename

# train or test tag
int32 action
int32 TRAIN = 0
int32 TEST = 1

#observed reward from previous trial
float32 reward

---

# Return Training Samples
geometry_msgs/PointStamped[] training_centers

# Return Template indicies to match with centers and templates for parallelization
int32[] indicies

# Return with the point of action execution
geometry_msgs/PointStamped action_location

# Whether feature extraction failed or succeeded
int32 FAILURE = 1
int32 SUCCESS = 2
int32 result
